// <auto-generated />
using System;
using L4GA.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260405125152_ReestructuracionLogistica4Etapas")]
    partial class ReestructuracionLogistica4Etapas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("L4GA.Backend.Models.Operacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("HoraArriboCremer")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraArriboGreen")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraArriboPuerto")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraCargaBioGreen")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraCargaNeutroCremer")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraDescargaGreen")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraEquipoListoGreen")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraInPlantaGreen")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraInUnidadPuerto")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraOutCremer")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraOutGreen")
                        .HasColumnType("time(6)");

                    b.Property<decimal?>("LitrosCremer")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("LitrosRecibidosPuerto")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("PesajePuerto")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("PesoCargadoCremer")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("PesoGreenEgreso")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("PesoGreenIngreso")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("PesoRecibidoPuerto")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("PesoTotalCremer")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("TaraCremer")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("TrackingLink")
                        .HasColumnType("longtext");

                    b.Property<int>("TransporteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VolCargadoGreen")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("VolDescargadoGreen")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("TransporteId");

                    b.ToTable("Operaciones");
                });

            modelBuilder.Entity("L4GA.Backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("L4GA.Models.Nomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActividad")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LinkTracking")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Nominas");
                });

            modelBuilder.Entity("L4GA.Models.Transporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnioCisterna")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AnioTracto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Chofer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cisterna")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Contacto")
                        .HasColumnType("longtext");

                    b.Property<string>("Tracto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Transportes");
                });

            modelBuilder.Entity("NominaTransporte", b =>
                {
                    b.Property<int>("NominasId")
                        .HasColumnType("int");

                    b.Property<int>("TransportesId")
                        .HasColumnType("int");

                    b.HasKey("NominasId", "TransportesId");

                    b.HasIndex("TransportesId");

                    b.ToTable("NominaTransportes", (string)null);
                });

            modelBuilder.Entity("L4GA.Backend.Models.Operacion", b =>
                {
                    b.HasOne("L4GA.Models.Transporte", "Transporte")
                        .WithMany()
                        .HasForeignKey("TransporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("NominaTransporte", b =>
                {
                    b.HasOne("L4GA.Models.Nomina", null)
                        .WithMany()
                        .HasForeignKey("NominasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L4GA.Models.Transporte", null)
                        .WithMany()
                        .HasForeignKey("TransportesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
