// <auto-generated />
using System;
using L4GA.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260318125830_AddNominaTable")]
    partial class AddNominaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("L4GA.Backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("L4GA.Models.Nomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActividad")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Nominas");
                });

            modelBuilder.Entity("L4GA.Models.Transporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnioCisterna")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AnioTracto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Chofer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cisterna")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NominaId")
                        .HasColumnType("int");

                    b.Property<string>("Tracto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NominaId");

                    b.ToTable("Transportes");
                });

            modelBuilder.Entity("L4GA.Models.Transporte", b =>
                {
                    b.HasOne("L4GA.Models.Nomina", null)
                        .WithMany("Transportes")
                        .HasForeignKey("NominaId");
                });

            modelBuilder.Entity("L4GA.Models.Nomina", b =>
                {
                    b.Navigation("Transportes");
                });
#pragma warning restore 612, 618
        }
    }
}
